// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiounhvoehicjbyxbpbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb3VuaHZvZWhpY2pieXhicGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjE0MjYsImV4cCI6MjA2MjE5NzQyNn0.011wIIayFy-ikhUyCZLtNGek3ZpDM4VorUz0-4bKL3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);